sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  # g++4.8.1
  # - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # - sudo apt-get update -qq

install:
  # g++4.8.1
  # - if [ "$CXX" = "g++" ]; then sudo apt-get install -y g++-4.8; fi
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
 # NOTE: trick used here since Travis CI only seems to check the last command result.
 - rm -f checkV8Result
 - ./configure && make
 - CITEST=yup make test-simple && echo ok >> checkV8Result
 - ./configure --engine-mozilla && make
 - CITEST=yup make test-simple && cat checkV8Result
