os:
  - linux
  - osx

language:
  - cpp

compiler:
  - gcc

script:
 # NOTE: trick used here since Travis CI only seems to check the last command result.
 - rm -f checkV8Result
 - ./configure && make
 - CITEST=yup make test-simple && echo ok >> checkV8Result
 - ./configure --engine-mozilla && make
 - CITEST=yup make test-simple && cat checkV8Result
